sonar.projectKey=chorizus_frontend-ia
sonar.organization=chorizus


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=frontend-ia
#sonar.projectVersion=1.0


# --- Rutas de Análisis ---
# '.' significa que analice la carpeta donde está este archivo
sonar.sources=/tfg/cursor/landing primera version

# IMPORTANTE: Indica que este proyecto es para entorno Web (Browser)
# Esto ayuda a Sonar a no marcar 'document' o 'window' como errores
sonar.javascript.environments=browser

# --- Exclusiones (Para que la nota sea real) ---
# Ignoramos librerías externas o carpetas de dependencias
sonar.exclusions=node_modules/**, dist/**, vendor/**

# --- Codificación ---
sonar.sourceEncoding=UTF-8